### ISSUE TITLE
Positioning the chips

### ISSUE THREAD

**Issue by nisozakuto** [nisozakuto/Blackjack#2]
I am not able to position the chips in a way I want to. The best I could do it to fix it to the left bottom. 
I would like them to be bottom center and stay there regardless of the window's size.

![chiparefixed](https://user-images.githubusercontent.com/13414913/88328678-ce193100-ccf6-11ea-87ed-0da0f6207f84.gif)

The chips are in a div called "ChipsArea" Which is under "HTML>Body>Main"

The css for it looks like this: 
```
.chipsArea {
    position: absolute;
    bottom: 60px;
    left: 30px;
    margin: 0 auto;

}
```

The repo is up to date.

**Comment by pmacaluso3** [comment]
I reference this post every time I am trying to use `margin: 0 auto` and it is not working:

https://stackoverflow.com/questions/4955122/what-exactly-is-needed-for-margin-0-auto-to-work

You will need to give it a position that is not absolute (which will make left: 30px no longer needed), and you will need to give it a real height and width (for example, 100px and 400px). The problem you're having now is in two parts: the position absolute is incompatible with margin auto, and because it is a block-level element without a specified width, it takes up the whole width of its container (1200px in the attached image). So there is no leftover horizontal space to cut in half and turn into margins.

![Screen Shot 2020-07-23 at 3 31 04 PM](https://user-images.githubusercontent.com/10779838/88330733-d45cdc80-ccf9-11ea-8c18-3c1b55a77a79.png)

**Comment by nisozakuto** [comment]
This helped me fix the issue, I needed to change the div above the `chipsArea` 
Height is not responsive for now, but I am satisfied for now. I will revisit it when I have more time. 
Thanks!
